export const products = [
  {
    id: "p1",
    name: "Wireless Headphones",
    price: 79.99,
    image: "🎧",
    category: "Audio",
    description: "Noise-cancelling over-ear headphones with 30hr battery life.",
  },
  {
    id: "p2",
    name: "Mechanical Keyboard",
    price: 129.99,
    image: "⌨️",
    category: "Peripherals",
    description: "Cherry MX switches, RGB backlight, aluminum frame.",
  },
  {
    id: "p3",
    name: "USB-C Hub",
    price: 49.99,
    image: "🔌",
    category: "Accessories",
    description: "7-in-1 hub with HDMI, SD card, and 100W passthrough charging.",
  },
  {
    id: "p4",
    name: "Webcam HD",
    price: 64.99,
    image: "📷",
    category: "Peripherals",
    description: "1080p autofocus webcam with built-in microphone and privacy cover.",
  },
  {
    id: "p5",
    name: "Laptop Stand",
    price: 39.99,
    image: "💻",
    category: "Accessories",
    description: "Adjustable aluminum stand, foldable, supports up to 17 inch.",
  },
  {
    id: "p6",
    name: "Portable Speaker",
    price: 54.99,
    image: "🔊",
    category: "Audio",
    description: "Waterproof Bluetooth speaker, 12hr battery, surprisingly loud.",
  },
];
